<a href="https://colab.research.google.com/github/ajaysaikiran2208/PyTorch/blob/main/Linear_regression_using_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Linear Regression In Pytorch

In [2]:
import torch
import numpy as np

In [4]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 59], 
                   [87, 134, 68], 
                   [102, 43, 37], 
                   [70, 96, 79]], dtype='float32')
                   
# Targets (rice, wheat)
targets = np.array([[62, 71], 
                    [91, 102], 
                    [109, 123], 
                    [34, 43], 
                    [99, 111]], dtype='float32')

In [5]:
# Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  59.],
        [ 87., 134.,  68.],
        [102.,  43.,  37.],
        [ 70.,  96.,  79.]])
tensor([[ 62.,  71.],
        [ 91., 102.],
        [109., 123.],
        [ 34.,  43.],
        [ 99., 111.]])


In [6]:
# Weights and biases
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[ 1.0089, -0.9404,  0.7329],
        [-0.9061, -0.8904,  0.7880]], requires_grad=True)
tensor([-0.3367, -0.3290], requires_grad=True)


In [7]:
def model(x):
    return x @ w.t() + b

In [8]:
# Generate predictions
preds = model(inputs)
print(preds)

tensor([[  41.8205,  -92.2511],
        [  51.9585, -114.6522],
        [  11.2598, -144.8953],
        [  89.2516, -101.8871],
        [  37.9057,  -86.9857]], grad_fn=<AddBackward0>)
