<a href="https://colab.research.google.com/github/ajaysaikiran2208/PyTorch/blob/main/PyTorch_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Basics of **PyTorch**

In [ ]:
import torch

In [2]:
t1=torch.tensor(4.)
t1


tensor(4.)

In [3]:
t1.dtype

torch.float32

In [4]:
t2=torch.tensor([1.,2,3,4])
t2

tensor([1., 2., 3., 4.])

In [6]:
t3=torch.tensor([[1,2],[3,4],[5.,6]])
t3

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [8]:
t3.size()

torch.Size([3, 2])

In [9]:
t3.shape

torch.Size([3, 2])

Tensor Operations and gradient

In [12]:
x=torch.tensor(3.)
w=torch.tensor(4.,requires_grad=True)
b=torch.tensor(5.,requires_grad=True)

In [15]:
# Arithmetic operations

y=w*x+b
y

tensor(17., grad_fn=<AddBackward0>)

In [16]:
# Compute derivatives
y.backward()

In [17]:
print("dy/dx",x.grad)
print("dy/dw",w.grad)
print("dy/db",b.grad)

dy/dx None
dy/dw tensor(3.)
dy/db tensor(1.)


Tensor functions

In [19]:
t6=torch.full((3,2),42)
t6

tensor([[42, 42],
        [42, 42],
        [42, 42]])

In [22]:
# Concatenate two tensors with compatible shapes
t7=torch.cat((t3,t6))
t7

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [42., 42.],
        [42., 42.],
        [42., 42.]])

In [24]:
t8=torch.sin(t7)
t8

tensor([[ 0.8415,  0.9093],
        [ 0.1411, -0.7568],
        [-0.9589, -0.2794],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165]])

In [27]:
t9=t8.reshape(3,2,2)
t9

tensor([[[ 0.8415,  0.9093],
         [ 0.1411, -0.7568]],

        [[-0.9589, -0.2794],
         [-0.9165, -0.9165]],

        [[-0.9165, -0.9165],
         [-0.9165, -0.9165]]])